# Site settings
title: "DJ-Rowin"
# tagline: "DJ-Rowin!!"
url: "https://djrowin.nl" # The base hostname & protocol for your site. Use it if you need absolute URL's
description: "DJ Rowin, voor alle feesten in en rondom Amsterdam en Purmerend. DJ Rowin staat gelijk aan een heel dik feest"

# Social
socialimg: /images/social-rowin.jpg # be sure to change this image
facebook: rowin.mol
twitter: rowin648
github: rowin1125
instagram: rowin648

# Contact
phone: "0642655790"
email: "info@djrowin.nl"

# Use this for production
sass:
  sass_dir: _sass
  style: compressed

source: "./src"
destination: "./docs"

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "blog/page:num/"
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock

# Blog settings

# Lang settings
default_lang: 'en'
langs:
  'en': 'English'
lang_codes:
  - 'en'
