# Site settings
title: "DJ-Rowin"
tagline: "DJ-Rowin!!"
url: "htpps://djrowin.nl" # The base hostname & protocol for your site. Use it if you need absolute URL's

# Social
socialimg: /img/social.jpg # be sure to change this image
facebook: fbusername
twitter: twusername
github: rowin1125
googleplus: gusername
instagram: igusername

# Contact
phone: "0642655790"
email: "info@djrowin.nl"

# Use this for production
sass:
  sass_dir: css
  #style: compressed

source: "./src"
destination: "./out"

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "blog/page:num/"
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock

# Blog settings

# Lang settings
default_lang: 'en'
langs:
  'en': 'English'
lang_codes:
  - 'en'
